### ISSUE TITLE
`unknown test file type` error thrown

### ISSUE THREAD

**Issue by Aanchal-Jain-Apica** [test-summary/action#12]
I have a .NET framework project with unit tests running with NUnit. It generates a test result file as `NUnitResults.xml`. In my GitHub workflow file I have a step for test-summary after running the tests as follows - 
```
- name: Test Summary
        uses: test-summary/action@v1.0
        if: always()
        with:
          paths: "./NUnitResults.xml"
```

But this steps throws an error as  `unknown test file type for './NUnitResults.xml'`
